# Generated by Django 5.2.2 on 2025-06-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data Records',
                'db_table': 'market_data',
                'ordering': ['date'],
                'unique_together': {('date', 'symbol')},
            },
        ),
    ]
