# Generated by Django 5.2.2 on 2025-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='distribution',
            new_name='current_distribution',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='initial_distribution',
            field=models.JSONField(default=dict),
        ),
    ]
