# Generated by Django 5.2.2 on 2025-10-17 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_distribution_portfolio_current_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('distribution', models.JSONField(default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='api.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Tracking',
                'verbose_name_plural': 'Portfolio Tracking Records',
                'db_table': 'portfolio_tracking',
                'ordering': ['date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
