# Generated by Django 5.2.2 on 2025-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portfoliotracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotracking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
